// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minigames.Persistence.Data;

#nullable disable

namespace Minigames.Persistence.Migrations
{
    [DbContext(typeof(MinigamesDbContext))]
    partial class MinigamesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Minigames.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Minigames.Domain.Entities.Player", b =>
                {
                    b.OwnsOne("Minigames.Domain.Entities.PlayerGameSummary", "GameSummary", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("int");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");

                            b1.OwnsOne("Minigames.Domain.Entities.FormulaGameResult", "FormulaGameResult", b2 =>
                                {
                                    b2.Property<int>("PlayerGameSummaryPlayerId")
                                        .HasColumnType("int");

                                    b2.Property<int?>("BestDifference")
                                        .HasColumnType("int");

                                    b2.Property<int>("TimesPlayed")
                                        .HasColumnType("int");

                                    b2.HasKey("PlayerGameSummaryPlayerId");

                                    b2.ToTable("Players");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerGameSummaryPlayerId");
                                });

                            b1.OwnsOne("Minigames.Domain.Entities.HangmanGameResult", "HangmanGameResult", b2 =>
                                {
                                    b2.Property<int>("PlayerGameSummaryPlayerId")
                                        .HasColumnType("int");

                                    b2.Property<int>("TimesPlayed")
                                        .HasColumnType("int");

                                    b2.Property<int>("TimesWon")
                                        .HasColumnType("int");

                                    b2.HasKey("PlayerGameSummaryPlayerId");

                                    b2.ToTable("Players");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerGameSummaryPlayerId");
                                });

                            b1.Navigation("FormulaGameResult")
                                .IsRequired();

                            b1.Navigation("HangmanGameResult")
                                .IsRequired();
                        });

                    b.Navigation("GameSummary")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
